---
  redisServer:
      type: string
      description: "IP Address or Hostname of Redis Server" 
      required: true
  redisPort:
      type: integer
      description: "Port of Redis Server" 
      required: true
